package com.stoicprogrammer.qtrqth.model;

import com.stoicprogrammer.qtrqth.ntp.NtpResponse;
import com.stoicprogrammer.qtrqth.nmea.GpsData;
import com.stoicprogrammer.qtrqth.util.GridSquareCalculator;
import org.slf4j.Logger;
import org.slf4j.MDC;

import java.time.Instant;
import java.util.Optional;

/**
 * The 'Pulse' is the fundamental domain model of the qtr-qth system.
 * It represents the high-fidelity confluence of GPS telemetry and NTP reference.
 */
public record TelemetryPulse(
    String pulseId, 
    String triggeringSentence, 
    Instant ingressTime,
    GpsData data, 
    NtpResponse reference,
    ConfluenceHealth health
) {
    // Mask for 16-bit Pulse ID generation
    private static final int PULSE_ID_MASK = 0xFFFF;

    /**
     * Factory method to initiate a new telemetry heartbeat from a triggering sentence.
     */
    public static TelemetryPulse start(
        final String trigger, 
        final NtpResponse ntp, 
        final ConfluenceHealth health,
        final Instant ingressTime,
        final GpsData enrichedData
    ) {
        final String id = String.format("%04X", (trigger.hashCode() & PULSE_ID_MASK));
        return new TelemetryPulse(id, trigger, ingressTime, enrichedData, ntp, health);
    }

    /**
     * Verifies if the pulse carries a valid GPS fix.
     */
    public boolean hasValidFix() {
        return Optional.ofNullable(data)
            .flatMap(d -> Optional.ofNullable(d.utcTime()))
            .isPresent();
    }

    /**
     * Identifies if this pulse was generated by a system heartbeat/sentinel.
     */
    public boolean isHeartbeat() {
        return triggeringSentence.equals(TelemetryEvent.SIGNAL_LOSS.rawSentence());
    }

    /**
     * Logs the final high-fidelity telemetry result within the pulse's diagnostic context.
     */
    public void logFinal(final Logger log) {
        runWithContext(() -> {
            final String grid = GridSquareCalculator.calculate(data.latitude(), data.longitude());
            final String ntpStatus = Optional.ofNullable(reference)
                .map(r -> String.format("NTP: %s (RTT: %dms, Stratum: %d)", r.time(), r.rttMs(), r.stratum()))
                .orElse("NTP: No Reference");
            
            final String healthMsg = String.format("[%s | GPS:%s | NTP:%s | Mode:%s]", 
                health.syncStatus(), health.gpsStatus(), health.ntpStatus(), health.mode());
            
            log.info("{} Fix: {} | {} | Grid: {}", healthMsg, data, ntpStatus, grid);
        });
    }

    /**
     * Helper to execute operations within the Mapped Diagnostic Context (MDC).
     */
    private void runWithContext(final Runnable action) {
        MDC.put("pulseId", pulseId);
        try {
            action.run();
        } finally {
            MDC.clear();
        }
    }
}
