# URL settings
url: "https://n8qqq.github.io"
baseurl: "/qtr-qth"
permalink: pretty

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Relative Links settings
relative_links:
  enabled: true
  collections: true

# Exclude files from processing
exclude:
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata/
  - Gemfile
  - Gemfile.lock
